services:
  web:
    build:
      context: .
      target: local
    ports:
      - "5000:5000"
    volumes:
      - ./:/opt/python-api
  tests:
    build:
      context: .
      target: local
    command: [ "ptw" ]
    volumes:
      - ./:/opt/python-api

